### ISSUE TITLE
A lot of errors with GdbHandleEvent

### ISSUE THREAD

**Issue by Diadlo** [sakhnik/nvim-gdb#104]
Sometimes I have errors like this. What can be the reason?

https://asciinema.org/a/equKN8JWWTVtkYZzEUa2Yz0xE

**Comment by sakhnik** [comment]
I wonder whether any exception rises in the code. If you set the environment variable `NVIMGDB_LOGFILE=/tmp/log.txt`, does the file `/tmp/log.txt` contain anything error-like after running?

**Comment by Diadlo** [comment]
`[Gdb] GdbHandleEvent: Vim(normal):Can't re-enter normal mode from terminal mode`

And seems logger breaks too after this error, because it doesn't log next commands and error occupations

**Comment by Diadlo** [comment]
Ok. It looks like kind of a conflict with my `init.vim`

**Comment by Diadlo** [comment]
Ok. Looks like it's kind of conflict with opened tagbar from `majutsushi/tagbar`.

**Comment by sakhnik** [comment]
Unfortunately, I'm unable to reproduce this. The tagbar window appears just well for me.
Although, I've noticed that the plugin nvim-gdb fails (similarly to what's described in this ticket) right after update on the first launch. But when I quit neovim and open it again, the error doesn't come back.

**Comment by Diadlo** [comment]
@sakhnik But the first time it's still an issue, isn't it?

I feel like I have a specific binary file + state of gdb server to reproducible. And I can try to check something if you need

**Comment by sakhnik** [comment]
I suspect there is something between Python interpreter and Neovim. Let's start from the beginning. What's the first error reported by `:messages`? Would you be able to put more logs into the Python script to find out what is the first place where the error appears?

**Comment by Diadlo** [comment]
`:messages` produce the same errors
![image](https://user-images.githubusercontent.com/6306608/75032877-a1988900-54ba-11ea-9f77-be1bd2590fe0.png)

**Comment by Diadlo** [comment]
Not sure, what happens, but in [Gdb._get_app](https://github.com/sakhnik/nvim-gdb/blob/master/rplugin/python3/gdb/__init__.py#L22) handle not always accessible. Sometimes it failed to get `tagpage`, sometimes it failed to get `handler` itself. 

With debug code like this:
```
debug(f'current.tabpage.handle = {current.tabpage.handle}')
current.tabpage.handle
debug('before assignment')
handle = current.tabpage.handle
debug(f'handle = {handle}')
```

I have an output:
```
current.tabpage.handle = 2
before assignment
```

**Comment by Diadlo** [comment]
Ok. I just give up and remove `autocmd`

**Comment by Diadlo** [comment]
And just found that currently have this problem even without `autocmd`

**Comment by sakhnik** [comment]
That's strange. It looks like a bug in neovim or pynvim. Unfortunately, I have no idea what's wrong.

**Comment by sakhnik** [comment]
Could you please retest after updating `master`?

**Comment by Diadlo** [comment]
@sakhnik Ok. I will try

**Comment by Diadlo** [comment]
Looks like fixed in `master`. Close for now

**Comment by sakhnik** [comment]
I'm glad to know that. It's interesting that I didn't fix anything specific, just added handling for `:tabclose`, made sure no exceptions appear in the log.
Please let me know whether the upcoming changes (to be released soon) are to degrade the quality.
